name: Deploy Dashboard

on:
  push:
    branches: [ main ]
    paths:
      - 'outreach-bot/panel/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd outreach-bot/panel
        pip install -r requirements.txt
    
    - name: Deploy to Railway
      uses: railway/deploy@v1
      with:
        service: outreach-bot-dashboard
        token: ${{ secrets.RAILWAY_TOKEN }} 